# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/local/bin/

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./


# Install dependencies
RUN yarn install

# Copy the rest of yarnthe application code to the working directory
COPY . .

# Set the entrypoint to the script
COPY entrypoint.sh /usr/local/bin/

# Make the entrypoint script executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Make port 3000 available to the world outside this container
EXPOSE 4000

# ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Define the command to run the application



