apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /    
spec:
  rules:
  - host: auth.local #optional , This rule only applies to traffic coming to shafaq.com. If a request comes to shafaq.com, Kubernetes will use this rule to decide where to send the traffic.
    http:
      paths:
      - path: / #This means any URL that starts with / (which is all URLs in this case) will match this rule.
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 4000
  - host: web.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
  - host: adminer.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adminer-service
            port:
              number: 8080
