{{- $fullName := include "my-signup-app.fullname" . -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-auth
spec:
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-adminer
spec:
  selector:
    app: adminer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: {{ .Values.service.type }}
