version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432

  auth-service:
    build:
      context: ./backend/auth
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

  web:
      build:
        context: ./web
      ports:
        - 8081:80
      depends_on:
        - auth-service
      env_file:
        - .env

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pgdata:
