# Stage 1: Build the React app
FROM node:16 as builder
WORKDIR /app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn run build
# Stage 2: Create the production image
FROM nginx:latest
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] #daemon is off here bcz daemon is running all the time and nginx will not work as bg service , now daemon is off so nginx will work as foreground service and if we dont change it nginx will owrk as daemon service.
